apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app-pod

spec:
  containers:
  -name: postgres
   image: postgres:15.6
   ports:
   - containerPort: 5432
