apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app-pod

spec:
  containers:
  -name: worker-app
   image: dockersamples/exampleworkerapp_worker
     